### File: .github/workflows/main.yml
name: ML Model CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas numpy fastapi uvicorn joblib beautifulsoup4 requests

    - name: Train model
      run: |
        python train.py

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        scp -i ${{ secrets.EC2_KEY }} -r app/ ec2-user@<EC2_PUBLIC_IP>:/home/ec2-user/app/
        ssh -i ${{ secrets.EC2_KEY }} ec2-user@<EC2_PUBLIC_IP> 'nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &'
